name: EventPulse Backend CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  # -----------------------
  # CI
  # -----------------------

  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build


  # -----------------------
  # CD
  # -----------------------

  deploy:
    name: Deploy to EC2

    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |
          mkdir -p ~/.ssh

          printf '%s\n' "$EC2_SSH_KEY" > ~/.ssh/eventpulse_key

          chmod 600 ~/.ssh/eventpulse_key

          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts


      - name: Deploy EventPulse
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}

        run: |
          ssh -i ~/.ssh/eventpulse_key "$EC2_USER@$EC2_HOST" << 'EOF'

            set -e

            cd ~/EventPulse_BE

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            npm ci

            echo "Building application..."
            npm run build

            echo "Restarting application..."
            pm2 restart eventpulse-api

            pm2 save

            echo "Deployment complete!"

          EOF